# config.example.yaml - 配置文件模板
# 复制此文件为 config.yaml 并填入您的实际配置
# api_key: "YOUR_GEMINI_API_KEY" # 替换为您的 Gemini API 密钥
# 该配置文件用于设置文献综述生成器的参数和选项

# 使用支持 PDF 输入和长上下文的模型 (参考 Gemini 文档)
# 示例：
# gemini-2.0-flash-thinking-exp-01-21
# gemini-2.0-flash
# gemini-2.5-pro-preview-03-25
# gemini-2.0-flash-lite
# gemini-2.5-flash-preview-04-17

llm:
  model_name: "gemini-2.5-flash"                   # 用于文献总结的模型
  final_draft_model_name: "gemini-2.5-pro"         # (可选) 用于最终生成的模型，可能需要更强能力
  api_key: "YOUR_GEMINI_API_KEY"                   # 替换为您的 Gemini API 密钥，多个API密钥用逗号分隔
  temperature: 1.5                                 # 0.0 表示确定性输出，2.0 表示高度随机
  max_retries: 5                                   # 最大重试次数

paths:
  pdf_dir: "PDF_Files/" 
  txt_dir: "TXT_Files/"
  cache_file: "cache/summaries_cache.json"
  summary_output_file: "Results_Files/文献总结.json"
  final_output_file: "Results_Files/最终结果.txt"

prompts: # 文件名相对于 txt_dir
  research_theme: "研究主题.txt"
  summary_prompt: "文献总结提示词.txt"
  review_final_prompt: "文献综述撰写提示词.txt"
  qualitative_final_prompt: "定性研究论文撰写提示词.txt"
  references_list_file: "参考文献列表.txt"

# 缓存设置
cache:
  enabled: true